[build]
  command = "node app.js"
  functions = "."

[[redirects]]
  from = "/api/*"
  to = "/app/:splat"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
    Access-Control-Allow-Headers = "Content-Type"

[dev]
  functions = "."
